/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'StakingVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakingVault__factory>
getContractFactory(name: 'WTC_Coin', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WTC_Coin__factory>
getContractFactory(name: 'WTC_NFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WTC_NFT__factory>

  getContractAt(name: 'StakingVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakingVault>
getContractAt(name: 'WTC_Coin', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WTC_Coin>
getContractAt(name: 'WTC_NFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WTC_NFT>

  deployContract(name: 'StakingVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingVault>
deployContract(name: 'WTC_Coin', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WTC_Coin>
deployContract(name: 'WTC_NFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WTC_NFT>

  deployContract(name: 'StakingVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingVault>
deployContract(name: 'WTC_Coin', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WTC_Coin>
deployContract(name: 'WTC_NFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WTC_NFT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  