/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingVault } from './StakingVault.js';
export type { WTC_Coin } from './WTC_Coin.js';
export type { WTC_NFT } from './WTC_NFT.js';
export * as factories from './factories/index.js';
export { StakingVault__factory } from './factories/StakingVault__factory.js';
export { WTC_Coin__factory } from './factories/WTC_Coin__factory.js';
export { WTC_NFT__factory } from './factories/WTC_NFT__factory.js';