/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StakingVaultInterface extends Interface {
    getFunction(nameOrSignature: "DAILY_REWARD" | "calculateRewards" | "claimRewards" | "onERC721Received" | "ownerOfToken" | "rewardToken" | "stake" | "stakingNft" | "timestampStarted" | "unstake"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RewardsClaimed" | "Staked" | "Unstaked"): EventFragment;

    encodeFunctionData(functionFragment: 'DAILY_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateRewards', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'ownerOfToken', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingNft', values?: undefined): string;
encodeFunctionData(functionFragment: 'timestampStarted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DAILY_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOfToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingNft', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'timestampStarted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
  }

  
    export namespace RewardsClaimedEvent {
      export type InputTuple = [user: AddressLike, tokenId: BigNumberish, reward: BigNumberish];
      export type OutputTuple = [user: string, tokenId: bigint, reward: bigint];
      export interface OutputObject {user: string, tokenId: bigint, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [user: AddressLike, tokenId: BigNumberish, startedAt: BigNumberish];
      export type OutputTuple = [user: string, tokenId: bigint, startedAt: bigint];
      export interface OutputObject {user: string, tokenId: bigint, startedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [user: AddressLike, tokenId: BigNumberish, reward: BigNumberish];
      export type OutputTuple = [user: string, tokenId: bigint, reward: bigint];
      export interface OutputObject {user: string, tokenId: bigint, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingVault;
    waitForDeployment(): Promise<this>;

    interface: StakingVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DAILY_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    calculateRewards: TypedContractMethod<
      [user: AddressLike, tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    claimRewards: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    onERC721Received: TypedContractMethod<
      [operator: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >
    

    
    ownerOfToken: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingNft: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    timestampStarted: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    unstake: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DAILY_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateRewards'): TypedContractMethod<
      [user: AddressLike, tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [operator: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOfToken'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingNft'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'timestampStarted'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'RewardsClaimed'): TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;

    filters: {
      
      'RewardsClaimed(address,uint256,uint256)': TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
      RewardsClaimed: TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
    

      'Staked(address,uint256,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'Unstaked(address,uint256,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    
    };
  }