/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StakingVault__factory } from './StakingVault__factory.js';
export { WTC_Coin__factory } from './WTC_Coin__factory.js';
export { WTC_NFT__factory } from './WTC_NFT__factory.js';